### ISSUE TITLE
Use the new 'foxfood' keyword instead of 'dogfood'

### ISSUE THREAD

**Issue by edmorley** [mozilla-b2g/bzlite#25]
I added a new `foxfood` keyword to Bugzilla at drs' request. Bzlite should probably set that now, instead of dogfood:
https://github.com/mozilla-b2g/bzlite/blob/ef6488ecd68b9a3e68b16cb62f407c135ee250be/lib/views/create-bug.js#L213

**Comment by edmorley** [comment]
CC @drs

**Comment by MichaelKohler** [comment]
see https://bugzilla.mozilla.org/show_bug.cgi?id=117784, I'm working on a PR for this

**Comment by MichaelKohler** [comment]
sorry, wrong bug. the correct is https://bugzilla.mozilla.org/show_bug.cgi?id=1177843

**Comment by edmorley** [comment]
Closing this out to de-clutter my GitHub open issues dashboard since this repo is deprecated.
